### ISSUE TITLE
How to build this shape incremental game

### ISSUE THREAD

**Issue by Turtwiggy** [SpencerFelton/ShapeIncremental#1]
Excuse me kind sir, I have stumbled upon your humble git repository. Would you be so kind as to add instructions on how to build this marvellous creation you are making? Perhaps in the form of a readme. I would everso much appreciate it if you would take the time to do this. Your humble admirer, Turtwiggy.

Edit: Upon further dillydallying, I have found that I needed to run the .html file. Thank you for your hard work and I am excited to see the developements.

**Comment by SpencerFelton** [comment]
To a kinder sir,

I'll do you one better. I would suggest you clone the repository onto your
machine, and double click the "index.html" file. That should do it.

Please let me know how you get on.

Yours sincerely,
Spencer

**Comment by Turtwiggy** [comment]
Marvellous! Fantastic! Inspirational! These are a few of the words I have to describe you. Thank you for your quick and informative reply. The game really does adhere to the incremental genre feeling flawlessly. You as an author of this technology must have a deep and profound knowledge of the incremental genre, and I am excited to follow your work. 

Thank you sir wizard,
Turtwiggy
